name: Java CI with Maven

on:
  push:
    branches: [ "*", "!main"]
  pull_request:
    branches: [ "main" ]
    types:
      - opened
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx (Enables Layer Caching)
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker Images
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: TESTCONTAINERS_RYUK_DISABLED=true mvn -B verify --file pom.xml
